[project]
name = "InquirerPy"
version = "0.3.5"
description = "Python port of Inquirer.js (A collection of common interactive command-line user interfaces)"
authors = [
  {name = "Kevin Zhuang", email = "kevin7441@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["cli", "prompt-toolkit", "commandline", "inquirer", "development"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Unix",
  "Operating System :: Microsoft",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development",
  "Topic :: Software Development :: User Interfaces",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
]
requires-python = ">=3.10"
dependencies = [
  "prompt-toolkit>=3.0.28",
]

[project.urls]
Repository = "https://github.com/yolabingo/InquirerPy"
Documentation = "https://inquirerpy.readthedocs.io"

[project.optional-dependencies]
docs = [
  "Sphinx>=7.0",
  "furo>=2024.1.29",
  "sphinx-copybutton>=0.5",
  "sphinx-autobuild>=2024.2.4",
  "myst-parser>=3.0",
]
dev = [
  "pre-commit>=3.5",
]

[tool.hatch.build.targets.wheel]
packages = ["InquirerPy"]
artifacts = ["InquirerPy/py.typed"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"

[tool.pydocstyle]
match = "^(?!(.*(init|main))).*\\.py"
convention = "pep257"
add-ignore = "D107"
match_dir = "^(?!(example)).*"

[tool.coverage.run]
source = ["InquirerPy"]

[tool.coverage.report]
ignore_errors = true
exclude_lines = [
    "if TYPE_CHECKING:"
]
